# Generated by Django 5.2.7 on 2025-12-29 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Category',
            new_name='category',
        ),
    ]
