# Generated by Django 5.2.7 on 2025-12-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0002_rename_category_room_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='active',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
