# Generated by Django 5.2.7 on 2026-01-01 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0003_remove_category_active_remove_category_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingroom',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='booking',
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='check_out',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smarthotel.receipt'),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='smarthotel.receipt'),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
