# Generated by Django 5.2.7 on 2026-01-01 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0004_remove_bookingroom_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='smarthotel.category'),
        ),
    ]
