# Generated by Django 5.2.7 on 2026-01-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0005_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
