# Generated by Django 5.2.7 on 2026-01-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0006_alter_bookingroom_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='check_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
