# Generated by Django 5.2.7 on 2026-01-03 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0007_alter_bookingroom_check_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='user',
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='receipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Cash'), (2, 'Card'), (3, 'Wallet')], null=True),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='smarthotel.room'),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='smarthotel.service'),
        ),
    ]
