# Generated by Django 5.2.7 on 2026-01-06 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0008_remove_receipt_user_bookingroom_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='RoomCategory',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='category',
            new_name='room_category',
        ),
        migrations.AddField(
            model_name='service',
            name='service_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='smarthotel.servicecategory'),
            preserve_default=False,
        ),
    ]
