# Generated by Django 5.2.7 on 2026-01-10 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0009_servicecategory_rename_category_roomcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingservice',
            name='check_out',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='start_date',
        ),
        migrations.AddField(
            model_name='receipt',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthotel.room'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smarthotel.service'),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
