# Generated by Django 5.2.7 on 2026-01-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0010_remove_bookingservice_check_out_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingservice',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='bookingroom',
            name='receipt',
        ),
        migrations.RenameField(
            model_name='bookingroom',
            old_name='price_per_night',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='bookingservice',
            old_name='unit_price',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'E Wallet'), (2, 'Cash'), (3, 'Card')], default=1),
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Partial'), (3, 'Full')], default=1),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'E Wallet'), (2, 'Cash'), (3, 'Card')], default=1),
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Partial'), (3, 'Full')], default=1),
        ),
        migrations.DeleteModel(
            name='Receipt',
        ),
    ]
