# Generated by Django 5.2.7 on 2026-01-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0011_remove_bookingservice_receipt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'E Wallet'), (2, 'Cash'), (3, 'Card')]),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'E Wallet'), (2, 'Cash'), (3, 'Card')]),
        ),
    ]
