# Generated by Django 5.2.7 on 2026-01-11 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0012_alter_bookingroom_payment_method_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingroom',
            old_name='amount',
            new_name='price_per_night',
        ),
        migrations.RenameField(
            model_name='bookingservice',
            old_name='amount',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='bookingroom',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='bookingroom',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='bookingroom',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='bookingservice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='is_available',
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bookingroom',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smarthotel.booking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingservice',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smarthotel.booking'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('payment_method', models.CharField(choices=[('E_WALLET', 'E Wallet'), ('CASH', 'Cash'), ('CARD', 'Card')], max_length=20)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='smarthotel.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
