# Generated by Django 5.2.7 on 2026-01-11 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0013_rename_amount_bookingroom_price_per_night_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingroom',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rooms', to='smarthotel.booking'),
        ),
        migrations.AlterField(
            model_name='bookingroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_rooms', to='smarthotel.room'),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='smarthotel.booking'),
        ),
        migrations.AlterField(
            model_name='bookingservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='smarthotel.service'),
        ),
    ]
