# Generated by Django 5.2.7 on 2026-01-11 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0014_alter_bookingroom_booking_alter_bookingroom_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
