# Generated by Django 5.2.7 on 2026-01-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0016_alter_booking_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
