# Generated by Django 5.2.7 on 2026-01-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0017_receipt_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
