# Generated by Django 5.2.7 on 2026-01-14 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthotel', '0018_remove_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='expires_at',
        ),
    ]
